const cfg=window.KEDIAMANKU_SUPABASE||{},ready=cfg.url&&cfg.anonKey&&!cfg.anonKey.includes('PASTE_SUPABASE_ANON_PUBLIC_KEY_HERE'),sb=ready&&window.supabase?window.supabase.createClient(cfg.url,cfg.anonKey):null,bucket='kediamanku-images';
const $=s=>document.querySelector(s),auth=$('[data-auth-card]'),dash=$('[data-dashboard]'),warn=$('[data-config-warning]'),login=$('[data-login-form]'),loginStatus=$('[data-login-status]'),status=$('[data-global-status]'),tbody=$('[data-post-list]'),form=$('[data-blog-form]'),editor=$('[data-editor-title]'),search=$('[data-search]'),statusFilter=$('[data-status-filter]'),catFilter=$('[data-category-filter]'),modal=$('[data-preview-modal]'),previewContent=$('[data-preview-content]');
let posts=[],routeDone=false;
function setMsg(el,msg,type=''){if(!el)return;el.textContent=msg||'';el.classList.toggle('is-error',type==='error');el.classList.toggle('is-success',type==='success')}
function clean(v,n=3000){return String(v||'').replace(/\u0000/g,'').replace(/[\u0001-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').trim().slice(0,n)}
function req(v,l,n=3000){v=clean(v,n);if(!v)throw new Error(l+' wajib diisi.');return v}
function url(v){v=clean(v,900);if(!v)return null;if(/^(javascript|data|vbscript):/i.test(v))throw new Error('URL tidak aman.');return v}
function nil(v,n=3000){v=clean(v,n);return v||null}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)}
function uniqSlug(v){return slugify(v)+'-'+Date.now().toString(36).slice(-5)}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
function fd(){return Object.fromEntries(new FormData(form).entries())}
function el(t,c,txt){const e=document.createElement(t);if(c)e.className=c;if(txt!==undefined)e.textContent=txt;return e}
function tags(v){return String(v||'').split(',').map(x=>clean(x,48)).filter(Boolean).slice(0,12)}
function ext(f){return (f.name.split('.').pop()||({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'}[f.type]||'webp')).toLowerCase().slice(0,5)}
async function upload(title){const f=form.querySelector('[name="featured_file"]')?.files?.[0];if(!f)return null;if(!f.type.startsWith('image/'))throw new Error('Featured image harus berupa gambar.');if(f.size>5*1024*1024)throw new Error('Ukuran featured image maksimal 5MB.');const path=`blog/${slugify(title)}-${Date.now()}.${ext(f)}`;const {error}=await sb.storage.from(bucket).upload(path,f,{cacheControl:'31536000',upsert:false});if(error){if(error.message?.toLowerCase().includes('bucket not found'))throw new Error(`Storage bucket '${bucket}' belum dibuat.`);throw error}return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
function storagePath(v){try{const u=new URL(clean(v,1200)),m=`/storage/v1/object/public/${bucket}/`,i=u.pathname.indexOf(m);return i<0?null:decodeURIComponent(u.pathname.slice(i+m.length))}catch{return null}}
async function removeOld(a,b){const x=storagePath(a),y=storagePath(b);if(x&&x!==y)await sb.storage.from(bucket).remove([x])}
function parseBlocks(v){return String(v||'').split(/\n+/).map(l=>l.trim()).filter(Boolean).map(line=>{const m=line.match(/^([a-z0-9-]+)\s*:\s*(.*)$/i),type=(m?m[1]:'p').toLowerCase(),body=m?m[2]:line;if(type==='h2'||type==='h3')return{type,text:clean(body,220)};if(type==='quote')return{type:'quote',text:clean(body,700)};if(type==='list'||type==='ordered-list')return{type,items:body.split('|').map(i=>clean(i,220)).filter(Boolean).slice(0,12)};if(type==='image'){const [u,a]=body.split('|').map(x=>clean(x,900));return{type:'image',url:url(u),alt:a||'Kediamanku blog article image'}}return{type:'paragraph',text:clean(body,1400)}}).filter(b=>b.text||b.url||b.items?.length)}
function blocksText(blocks){return Array.isArray(blocks)?blocks.map(b=>{if(b.type==='h2'||b.type==='h3')return`${b.type}: ${b.text||''}`;if(b.type==='quote')return`quote: ${b.text||''}`;if(b.type==='list'||b.type==='ordered-list')return`${b.type}: ${(b.items||[]).join(' | ')}`;if(b.type==='image')return`image: ${b.url||''} | ${b.alt||''}`;return`p: ${b.text||''}`}).join('\n'):''}
function setField(n,v){const f=form.querySelector(`[name="${n}"]`);if(f&&f.type!=='file')f.value=v??''}
function reset(){form.reset();delete form.dataset.editId;delete form.dataset.previousImage;editor.textContent='Create Article';setField('author_name','Kediamanku Editorial Team');setField('author_role','Interior Design & Build');setField('read_time_minutes',4)}
function fill(p){form.dataset.editId=p.id;form.dataset.previousImage=p.featured_image||'';editor.textContent='Edit Article';setField('title',p.title);setField('slug',p.slug);setField('excerpt',p.excerpt);setField('category',p.category);setField('tags',(p.tags||[]).join(', '));setField('author_name',p.author_name||'Kediamanku Editorial Team');setField('author_role',p.author_role||'Interior Design & Build');setField('author_avatar',p.author_avatar);setField('featured_image',p.featured_image);setField('read_time_minutes',p.read_time_minutes||4);setField('content_blocks',blocksText(p.content));setField('seo_title',p.seo_title);setField('seo_description',p.seo_description);setField('seo_keywords',(p.seo_keywords||[]).join(', '));form.scrollIntoView({behavior:'smooth',block:'start'})}
function payload(state){const d=fd(),title=req(d.title,'Title',180),content=parseBlocks(d.content_blocks);if(!content.length)throw new Error('Article content wajib diisi.');return{title,slug:slugify(d.slug)||uniqSlug(title),excerpt:req(d.excerpt,'Excerpt',420),content,featured_image:null,author_name:nil(d.author_name,140)||'Kediamanku Editorial Team',author_role:nil(d.author_role,140)||'Interior Design & Build',author_avatar:url(d.author_avatar),category:req(d.category,'Category',80),tags:tags(d.tags),status:state,seo_title:nil(d.seo_title,180),seo_description:nil(d.seo_description,220),seo_keywords:tags(d.seo_keywords),read_time_minutes:Math.min(60,Math.max(1,Number(d.read_time_minutes)||4)),published_at:state==='published'?new Date().toISOString():null}}
async function save(state){const id=form.dataset.editId;if(id&&!uuid(id))throw new Error('Post id tidak valid.');setMsg(status,state==='published'?'Publishing article...':'Saving draft...');const p=payload(state),up=await upload(p.title);p.featured_image=up||url(fd().featured_image)||form.dataset.previousImage||null;if(id){const {error}=await sb.from('blog_posts').update(p).eq('id',id);if(error)throw error;await removeOld(form.dataset.previousImage,p.featured_image)}else{const {data,error}=await sb.from('blog_posts').insert(p).select('id').single();if(error)throw error;form.dataset.editId=data.id;form.dataset.previousImage=p.featured_image||''}setMsg(status,state==='published'?'Article published.':'Draft saved.','success');await load()}
function renderPreviewBlock(b){if(b.type==='h2'||b.type==='h3')return el(b.type,'',b.text);if(b.type==='quote')return el('blockquote','',b.text);if(b.type==='list'||b.type==='ordered-list'){const l=document.createElement(b.type==='ordered-list'?'ol':'ul');(b.items||[]).forEach(i=>l.append(el('li','',i)));return l}if(b.type==='image'){const im=document.createElement('img');im.src=b.url;im.alt=b.alt||'';return im}return el('p','',b.text)}
function preview(){const p=payload('draft');$('[data-preview-category]').textContent=p.category;$('[data-preview-title]').textContent=p.title;$('[data-preview-excerpt]').textContent=p.excerpt;previewContent.replaceChildren();p.content.forEach(b=>previewContent.append(renderPreviewBlock(b)));modal.classList.add('is-open');modal.setAttribute('aria-hidden','false')}
function closePreview(){modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true')}
function filtered(){const q=clean(search.value).toLowerCase(),st=statusFilter.value,cat=clean(catFilter.value).toLowerCase();return posts.filter(p=>`${p.title} ${p.excerpt||''} ${p.category} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q)&&(st==='all'||p.status===st)&&(!cat||p.category.toLowerCase().includes(cat)))}
function renderList(){const rows=filtered();tbody.replaceChildren();if(!rows.length){const r=document.createElement('tr'),c=el('td','','No articles found.');c.colSpan=4;r.append(c);tbody.append(r);return}rows.forEach(p=>{const r=document.createElement('tr'),a=document.createElement('td');a.append(el('strong','',p.title),el('span','',`${p.category} / ${p.slug}`));const s=document.createElement('td');s.append(el('span','status-pill '+(p.status==='published'?'is-published':''),p.status));const u=el('td','',new Date(p.updated_at||p.created_at).toLocaleDateString('id-ID')),ac=document.createElement('td'),box=el('div','row-actions');const e=el('button','','Edit');e.type='button';e.dataset.editId=p.id;const open=p.status==='published'?el('a','','Open'):el('button','','Preview');if(open.tagName==='A'){open.href='../../blog/detail/index.html?slug='+encodeURIComponent(p.slug);open.target='_blank';open.rel='noopener'}else{open.type='button';open.dataset.previewId=p.id}const del=el('button','delete','Delete');del.type='button';del.dataset.deleteId=p.id;del.dataset.deleteTitle=p.title;box.append(e,open,del);ac.append(box);r.append(a,s,u,ac);tbody.append(r)})}
async function load(){const {data,error}=await sb.from('blog_posts').select('*').order('updated_at',{ascending:false});if(error){const r=document.createElement('tr'),c=el('td','',error.message);c.colSpan=4;r.append(c);tbody.replaceChildren(r);return}posts=data||[];renderList();route()}
function route(){if(route.done)return;const p=new URLSearchParams(location.search),id=p.get('id');if(p.get('mode')==='new'){reset();route.done=true}else if(id&&uuid(id)){const post=posts.find(x=>x.id===id);if(post){fill(post);route.done=true}}}
async function del(id,title){if(!confirm(`Delete ${title}?`))return;const p=posts.find(x=>x.id===id),{error}=await sb.from('blog_posts').delete().eq('id',id);if(error){setMsg(status,error.message,'error');return}await removeOld(p?.featured_image,null);if(form.dataset.editId===id)reset();setMsg(status,'Article deleted.','success');await load()}
async function session(){const {data}=await sb.auth.getSession();auth.hidden=!!data.session;dash.hidden=!data.session;if(data.session)await load()}
if(!ready){warn.hidden=false;login.querySelectorAll('input,button').forEach(x=>x.disabled=true);setMsg(loginStatus,'Masukkan Supabase config dulu.','error')}
login.addEventListener('submit',async e=>{e.preventDefault();setMsg(loginStatus,'Logging in...');const d=Object.fromEntries(new FormData(login).entries()),{error}=await sb.auth.signInWithPassword({email:d.email,password:d.password});if(error)return setMsg(loginStatus,error.message,'error');login.reset();setMsg(loginStatus,'Login berhasil.','success');session()});
$('[data-logout]').addEventListener('click',async()=>{await sb.auth.signOut();auth.hidden=false;dash.hidden=true});
form.addEventListener('submit',async e=>{e.preventDefault();try{await save(e.submitter?.dataset.publish!==undefined?'published':'draft')}catch(err){setMsg(status,err.message,'error')}});
$('[data-preview]').addEventListener('click',()=>{try{preview()}catch(err){setMsg(status,err.message,'error')}});document.querySelectorAll('[data-close-preview]').forEach(b=>b.addEventListener('click',closePreview));
$('[data-new-post]').addEventListener('click',()=>{reset();history.pushState?.(null,'','index.html?mode=new');form.scrollIntoView({behavior:'smooth',block:'start'})});$('[data-reset-form]').addEventListener('click',reset);[search,statusFilter,catFilter].forEach(i=>i.addEventListener('input',renderList));
tbody.addEventListener('click',e=>{const ed=e.target.closest('[data-edit-id]'),pv=e.target.closest('[data-preview-id]'),rm=e.target.closest('[data-delete-id]');if(ed){const p=posts.find(x=>x.id===ed.dataset.editId);if(p){fill(p);history.pushState?.(null,'',`index.html?id=${encodeURIComponent(p.id)}`);setMsg(status,'Edit mode aktif.','success')}}else if(pv){const p=posts.find(x=>x.id===pv.dataset.previewId);if(p){fill(p);preview()}}else if(rm)del(rm.dataset.deleteId,rm.dataset.deleteTitle)});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePreview()});
if(sb){sb.auth.onAuthStateChange(()=>session());session()}
