const cfg=window.KEDIAMANKU_SUPABASE||{};
const $=(s)=>document.querySelector(s);
const page=$('[data-blog-page]'),content=$('[data-content]'),toc=$('[data-toc]'),popular=$('[data-popular-articles]'),related=$('[data-related-articles]');
const fallback='../../assets/images/hero-kitchen-living.webp';
function ok(){return cfg.restUrl&&cfg.anonKey&&!cfg.anonKey.includes('PASTE_SUPABASE_ANON_PUBLIC_KEY_HERE')}
function origin(){return /^https?:/.test(location.origin)?location.origin:'https://kediamanku.id'}
function slug(){const q=new URLSearchParams(location.search).get('slug');if(q)return q;const p=location.pathname.split('/').filter(Boolean),i=p.lastIndexOf('blog');return i>-1&&p[i+1]&&p[i+1]!=='detail'&&p[i+1]!=='index.html'?p[i+1]:(p[i+2]||'')}
function img(v){v=String(v||'').trim();if(!v||/^(javascript|data|vbscript):/i.test(v))return fallback;if(/^https?:\/\//i.test(v)||v.startsWith('../../')||v.startsWith('./'))return v;if(v.startsWith('../assets/'))return'../../'+v.slice(3);if(v.startsWith('/'))return'../..'+v;return'../../'+v.replace(/^\/+/,'')}
function clean(v,f=''){return String(v||'').replace(/\s+/g,' ').trim()||f}
function abs(p){return /^https?:/i.test(p)?p:new URL(p,origin()+'/blog/detail/').href}
function el(t,c,txt){const e=document.createElement(t);if(c)e.className=c;if(txt!==undefined)e.textContent=txt;return e}
function meta(sel,attr,val){if(!val)return;let m=document.head.querySelector(sel);if(!m){m=document.createElement('meta');const n=sel.match(/\[name="([^"]+)"\]/),p=sel.match(/\[property="([^"]+)"\]/);if(n)m.name=n[1];if(p)m.setAttribute('property',p[1]);document.head.append(m)}m.setAttribute(attr,val)}
function canonical(url){let l=document.head.querySelector('link[rel="canonical"]');if(!l){l=document.createElement('link');l.rel='canonical';document.head.append(l)}l.href=url}
function seo(post,image){const url=origin()+'/blog/'+encodeURIComponent(post.slug)+'/',title=post.seo_title||post.title+' | Kediamanku Blog',desc=clean(post.seo_description||post.excerpt,'Kediamanku interior design and build article.').slice(0,160);document.title=title;meta('meta[name="description"]','content',desc);meta('meta[name="keywords"]','content',[...(post.seo_keywords||[]),...(post.tags||[])].join(', '));canonical(url);meta('meta[property="og:type"]','content','article');meta('meta[property="og:title"]','content',title);meta('meta[property="og:description"]','content',desc);meta('meta[property="og:url"]','content',url);meta('meta[property="og:image"]','content',abs(image));meta('meta[name="twitter:card"]','content','summary_large_image');let s=document.head.querySelector('[data-blog-schema]');if(!s){s=document.createElement('script');s.type='application/ld+json';s.dataset.blogSchema='';document.head.append(s)}s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:desc,image:abs(image),datePublished:post.published_at,dateModified:post.updated_at||post.published_at,author:{'@type':'Organization',name:post.author_name||'Kediamanku Editorial Team'},publisher:{'@type':'Organization',name:'Kediamanku'},mainEntityOfPage:url})}
function blocks(post){return Array.isArray(post.content)?post.content:(post.content?.blocks||[{type:'paragraph',text:post.excerpt||'Article content will appear here.'}])}
function idify(v){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)}
function block(b){if((b.type==='h2'||b.type==='h3')&&clean(b.text)){const h=el(b.type,'',clean(b.text));h.id=b.id||idify(b.text);h.dataset.tocHeading='';return h}if(b.type==='quote')return el('blockquote','',clean(b.text));if(b.type==='list'||b.type==='ordered-list'){const l=document.createElement(b.type==='ordered-list'?'ol':'ul');(b.items||[]).map(clean).filter(Boolean).forEach(i=>l.append(el('li','',i)));return l.childElementCount?l:null}if(b.type==='image'){const im=document.createElement('img');im.src=img(b.url||b.src);im.alt=b.alt||'Kediamanku interior design article image';im.loading='lazy';return im}return clean(b.text)?el('p','',clean(b.text)):null}
function renderToc(){const hs=[...content.querySelectorAll('[data-toc-heading]')];toc.replaceChildren();if(!hs.length){toc.append(el('span','','Contents will appear after headings are added.'));return}hs.forEach(h=>{const a=el('a','',h.textContent);a.href='#'+h.id;a.dataset.level=h.tagName==='H3'?'3':'2';toc.append(a)});if('IntersectionObserver'in window){const links=[...toc.querySelectorAll('a')],io=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting)links.forEach(a=>a.classList.toggle('is-active',a.hash==='#'+en.target.id))}),{rootMargin:'-15% 0px -72% 0px'});hs.forEach(h=>io.observe(h))}}
function fmt(d){return d?new Intl.DateTimeFormat('en',{month:'long',day:'numeric',year:'numeric'}).format(new Date(d)):'Draft'}
function render(post){const image=img(post.featured_image);$('[data-breadcrumb-title]').textContent=post.title;$('[data-category]').textContent=post.category;$('[data-title]').textContent=post.title;$('[data-author-avatar]').src=img(post.author_avatar||'../../kediamanku-monogram.svg');$('[data-author-avatar]').alt=(post.author_name||'Kediamanku Editorial Team')+' avatar';$('[data-author-name]').textContent=post.author_name||'Kediamanku Editorial Team';$('[data-author-role]').textContent=post.author_role||'Interior Design & Build';$('[data-published-date]').textContent=fmt(post.published_at);$('[data-read-time]').textContent=(post.read_time_minutes||4)+' Min Read';$('[data-featured-image]').src=image;$('[data-featured-image]').alt=post.title+' by Kediamanku';content.replaceChildren();blocks(post).forEach(b=>{const n=block(b);if(n){n.dataset.reveal='';content.append(n)}});renderToc();seo(post,image);reveal()}
function link(post,card=false){const a=document.createElement('a');a.href='../detail/index.html?slug='+encodeURIComponent(post.slug);if(!card){a.textContent=post.title;return a}a.className='related-card';const im=document.createElement('img');im.src=img(post.featured_image);im.alt=post.title+' article by Kediamanku';im.loading='lazy';const c=document.createElement('div');c.append(el('span','',post.category),el('h3','',post.title));a.append(im,c);return a}
async function list(opts={}){const q=new URLSearchParams({select:'id,slug,title,category,excerpt,featured_image,published_at',status:'eq.published',order:'published_at.desc',limit:String((opts.limit||4)+1)});if(opts.category)q.set('category','eq.'+opts.category);const r=await fetch(cfg.restUrl+'/blog_posts?'+q,{headers:{apikey:cfg.anonKey,Authorization:'Bearer '+cfg.anonKey}});return r.ok?(await r.json()).filter(p=>p.slug!==opts.exclude).slice(0,opts.limit||4):[]}
async function side(post){const [p,r]=await Promise.all([list({exclude:post.slug,limit:5}),list({exclude:post.slug,category:post.category,limit:4})]);popular.replaceChildren();related.replaceChildren();if(!p.length)popular.append(el('span','','Popular articles will appear after more posts are published.'));p.forEach(x=>popular.append(link(x)));if(!r.length)related.append(el('p','blog-error','Related articles will appear after more posts are published.'));r.forEach(x=>related.append(link(x,true)))}
function error(m){page.replaceChildren(el('p','blog-error',m))}
function reveal(){const items=[$('.article-hero'),$('.featured-image'),...document.querySelectorAll('[data-reveal],.sidebar-card,.cta-card,.related-card')].filter(Boolean);items.forEach(i=>i.dataset.reveal='');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('is-visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -8% 0px'});items.forEach(i=>io.observe(i))}
document.querySelector('[data-toc-toggle]')?.addEventListener('click',e=>{const c=document.querySelector('.toc-card');c.classList.toggle('is-open');e.currentTarget.textContent=c.classList.contains('is-open')?'Close contents':'Open contents'});
(async()=>{const s=slug();if(!s)return error('Blog slug is missing.');if(!ok())return error('Supabase configuration is not active yet.');try{const q=new URLSearchParams({select:'*',slug:'eq.'+s,status:'eq.published',limit:'1'});const r=await fetch(cfg.restUrl+'/blog_posts?'+q,{headers:{apikey:cfg.anonKey,Authorization:'Bearer '+cfg.anonKey}});if(!r.ok)throw new Error('Blog article could not be loaded.');const rows=await r.json();if(!rows[0])return error('Article not found or not published.');render(rows[0]);side(rows[0])}catch(e){error(e.message)}})();
